######################################################
##
##  THE CLEVER CRIB | Home Assistant Configuration  
##  ----------------------------------------------
##  Outside: Back Yard
##  
##  I. HUBS
##    - None
##  II. COMPONENTS
##    - None
##  III. SESNORS
##    - Storage Shed
##  IV. CUSTOMIZATIONS
##    - Storage Shed
##  V. GROUPS
##    - Back Yard
##  VI. AUTOMATIONS
##    - None
##  VII. SCRIPTS
##    - None
##
##  Intent: Extend Security to Outside Back Yard Storage Shed
##  Status: On Hold    
##
######################################################

# Back Yard Devices

binary_sensor:
  - platform: mqtt
    state_topic: "smartthings/Storage Shed/contact/state"
    name: "Storage Shed"
    payload_on: open
    payload_off: closed
    
homeassistant:
  customize:
    binary_sensor.storage_shed:
      device_class: door
      icon: mdi:home
    
group:
  back_yard:
    name: Back Yard
    entities:
      - binary_sensor.storage_shed