
switch:
  - platform: mqtt
    name: "Entry Light"
    icon: mdi:lightbulb-outline
    state_topic: "smartthings/Entry Light/switch/state"
    command_topic: "smartthings/Entry Light/switch/cmd"
    payload_on: "on"
    payload_off: "off"

# Front Entrance Sensors
    
binary_sensor:
  - platform: mqtt
    state_topic: "smartthings/Front Entrance Door/contact/state"
    name: "Front Entrance Door"
    payload_on: open
    payload_off: closed
  - platform: mqtt
    state_topic: "smartthings/Front Entrance Door/acceleration/state"
    name: "Front Entrance Door Vibration"
    payload_on: active
    payload_off: inactive
  - platform: ring

sensor:
  - platform: mqtt
    state_topic: "smartthings/Front Entrance Door/temperature/state"
    name: "Front Entrance Door Temperature"
    unit_of_measurement: '°F'
  - platform: ring


# Front Entrance Interface
  
homeassistant:
  customize:
    binary_sensor.ring_front_doorbell_ding:
      icon: mdi:doorbell-video
    binary_sensor.front_door_lock:
      device_class: lock
    binary_sensor.front_entrance_door:
      device_class: door
    binary_sensor.front_entrance_door_vibration:
      device_class: vibration
    switch.entry_light:
      assumed_state: false
      
group:
  front_entrance_occupancy:
    name: Front Entrance Occupancy
    icon: mdi:account-multiple
    entities:
      - binary_sensor.ring_front_doorbell_motion
      - binary_sensor.ring_front_doorbell_ding
      - binary_sensor.front_entrance_door
  front_entrance_protection:
    name: Front Entrance Protection
    icon: mdi:security
    entities:
      - binary_sensor.front_entrance_door
  front_entrance:
    name: Front Entrance
    control: hidden
    entities:
      - camera.front_doorbell
      - group.front_entrance_occupancy
      - lock.front_door_lock
      - binary_sensor.ring_front_doorbell_ding
      - binary_sensor.ring_front_doorbell_motion
      - binary_sensor.front_entrance_door
      - binary_sensor.front_entrance_door_vibration
      - switch.entry_light
      - sensor.front_entrance_door_temperature
      - input_boolean.notify_front_entrance
      - input_boolean.security_front_entrance
  front_doorbell_status:
    name: Front Doorbell Status
    entities:
      - sensor.ring_front_doorbell_last_activity
      - sensor.ring_front_doorbell_last_ding
      - sensor.ring_front_doorbell_last_motion
      - sensor.ring_front_doorbell_battery
      - sensor.ring_front_doorbell_volume
      - sensor.ring_front_doorbell_wifi_signal_category
      - sensor.ring_front_doorbell_wifi_signal_strength
  front_door_lock_status:
    name: Front Door Lock Status
    entities:
      - sensor.schlage_be469_touchscreen_deadbolt_access_control
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_level
      - sensor.schlage_be469_touchscreen_deadbolt_alarm_type
      - sensor.schlage_be469_touchscreen_deadbolt_burglar
      - sensor.schlage_be469_touchscreen_deadbolt_power_management
      - sensor.schlage_be469_touchscreen_deadbolt_sourcenodeid
      - sensor.schlage_be469_touchscreen_deadbolt_system
    
# Front Entrance Interactivity
    
automation:
  - id: 'FrontEntranceOccupied'
    alias: Front Entrance Occupied
    initial_state: on
    trigger:
      platform: state
      entity_id: group.front_entrance_occupancy
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('alarm_control_panel.main_residence') not in ['armed_away','pending','triggered'] }}"
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
    action:
      service: switch.turn_on
      data:
        entity_id: switch.entry_light
  - id: 'FrontEntranceUnoccupied'
    alias: Front Entrance Unoccupied
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.front_entrance_occupancy
        to: 'off'
        for:
          minutes: 2
      - platform: state
        entity_id: lock.front_door_lock
        to: 'unlocked'
        for:
          minutes: 2
    condition:
      condition: state
      entity_id: group.front_entrance_occupancy
      state: 'off'
    action:
      - service: lock.lock
        entity_id: lock.front_door_lock
      - service: switch.turn_off
        data:
          entity_id: switch.entry_light
  - id: 'FrontDoorbellMotion'
    alias: Front Doorbell Motion
    initial_state: on
    trigger:
    - entity_id: binary_sensor.ring_front_doorbell_motion
      platform: state
      to: 'on'
    condition: []
    action:
    - service: script.notify
      data:
        tell: residents
        where: everywhere
        message: I have detected movement out front of the residence.
        inline_keyboard: 
          - 'View Image:/doorbell:image, Play Video:/doorbell:video'
          - 'Open Door:/frontdoor:open, Do Not Disturb:/frontdoor:dnd'
  - id: 'FrontDoorbellButton'
    alias: Front Doorbell Button
    initial_state: on
    trigger:
    - entity_id: binary_sensor.ring_front_doorbell_ding
      platform: state
      to: 'on'
    action:
    - service: script.notify
      data:
        tell: residents
        where: everywhere
        message: someone is waiting at the front door of the residence.
        inline_keyboard: 
          - 'View Image:/doorbell:image, Play Video:/doorbell:video'
          - 'Open Door:/frontdoor:open, Do Not Disturb:/frontdoor:dnd'
  - id: 'DoorUnlockedWithKeypad'
    alias: Door Unlocked With Keypad
    initial_state: on
    trigger:
      platform: state
      entity_id: lock.front_door_lock
      to: unlocked
    action:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state_attr('lock.front_door_lock', 'lock_status', 'Unlocked with Keypad by user 1') %} 
              script.kims_arrival
            {% elif is_state_attr('lock.front_door_lock', 'lock_status', 'Unlocked with Keypad by user 2') %} 
              script.williams_arrival
            {% elif is_state_attr('lock.front_door_lock', 'lock_status', 'Unlocked with Keypad by user 4') %} 
              script.jordans_arrival
            {% endif %}
  - id: 'FrontEntranceAlarm'
    alias: Front Entrance Alarm
    initial_state: on
    trigger:
    - entity_id: group.front_entrance_protection
      platform: state
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.security_front_entrance
          state: 'on'
        - condition: or
          conditions:
            - condition: state
              entity_id: alarm_control_panel.smart_security_system
              state: armed_home
            - condition: state
              entity_id: alarm_control_panel.smart_security_system
              state: armed_away
    action:
    - data:
        entity_id: alarm_control_panel.smart_security_system
      service: alarm_control_panel.alarm_trigger
      
script:
  williams_arrival:
    alias: William's Arrival
    sequence:
      - condition: state
        entity_id: alarm_control_panel.lower_residence
        state: armed_away
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.lower_residence
      - wait_template: "{{ is_state('group.williams_presence', 'home') }}"
        timeout: '00:03:00'
      - service: script.notify
        data:
          tell: william
          welcome: true
      - delay: '00:00:01'
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.main_residence
      - delay: '00:00:01'
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.lower_residence
  jordans_arrival:
    alias: Jordan's Arrival
    sequence:
      - condition: state
        entity_id: alarm_control_panel.upper_residence
        state: armed_away
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.upper_residence
      - wait_template: "{{ is_state('group.jordans_presence', 'home') }}"
        timeout: '00:03:00'
      - service: script.notify
        data:
          tell: jordan
          welcome: true
      - delay: '00:00:01'
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.main_residence
      - delay: '00:00:01'
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.upper_residence