# Living Room Devices

light:
  - platform: mqtt
    name: "Living Room Floor Lamp"
    command_topic: "smartthings/Living Room Floor Lamp/switch/cmd"
    brightness_command_topic: "smartthings/Living Room Floor Lamp/level/cmd"
    brightness_state_topic: "smartthings/Living Room Floor Lamp/level/state"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    state_topic: "smartthings/Living Room Floor Lamp/switch/state"
    
switch:
  - platform: mqtt
    name: Living Room Television Off
    icon: mdi:television
    command_topic: "smartthings/[TV] Living Room/switch/cmd"
    payload_off: "off"
  - platform: wake_on_lan
    name: Living Room Television
    mac_address: "5C-49-7D-E4-D6-E0"
    turn_off:
      service: switch.turn_off
      entity_id: switch.living_room_television_off
    
# Living Room Sensors

binary_sensor:
  - platform: mqtt
    state_topic: "smartthings/Living Room Outside Window/contact/state"
    name: "Living Room Outside Window"
    payload_on: open
    payload_off: closed
  - platform: mqtt
    state_topic: "smartthings/Living Room Outside Window/acceleration/state"
    name: "Living Room Outside Window Vibration"
    payload_on: active
    payload_off: inactive
  - platform: mqtt
    state_topic: "smartthings/Living Room Inside Window/contact/state"
    name: "Living Room Inside Window"
    payload_on: open
    payload_off: closed
  - platform: mqtt
    state_topic: "smartthings/Living Room Inside Window/acceleration/state"
    name: "Living Room Inside Window Vibration"
    payload_on: active
    payload_off: inactive
  - platform: mqtt
    state_topic: "smartthings/Living Room/motion/state"
    name: "Living Room Motion"
    payload_on: active
    payload_off: inactive
  - platform: mqtt
    state_topic: "smartthings/Litter Box Pan/contact/state"
    name: "Litter Box Pan"
    payload_on: open
    payload_off: closed
    
sensor:
  - platform: mqtt
    state_topic: "smartthings/Living Room Inside Window/temperature/state"
    name: "Living Room Inside Window Temperature"
    unit_of_measurement: '°F'
  - platform: mqtt
    state_topic: "smartthings/Living Room Outside Window/temperature/state"
    name: "Living Room Outside Window Temperature"
    unit_of_measurement: '°F'
  - platform: mqtt
    state_topic: "smartthings/Living Room/temperature/state"
    name: "Living Room Motion Temperature"
    unit_of_measurement: '°F'
  - platform: mqtt
    state_topic: "smartthings/Pet Water Fountain/power/state"
    name: "Pet Water Fountain"
    unit_of_measurement: 'W'
  - platform: mqtt
    state_topic: "smartthings/Litter Box/power/state"
    name: "Litter Box"
    unit_of_measurement: 'W'

input_datetime:
  litter_emptied:
    name: Litter Emptied
    icon: mdi:paw
    has_date: true
    
# Living Room Interface
    
homeassistant:
  customize:
    automation.pets_without_litter_notification:
      icon: mdi:paw
      friendly_name: Pets Without Litter
    automation.pets_without_water_notification:
      icon: mdi:cup-water
      friendly_name: Pets Without Water
    binary_sensor.living_room_inside_window:
      device_class: window
    binary_sensor.living_room_inside_window_vibration:
      device_class: vibration
    binary_sensor.living_room_outside_window:
      device_class: window
    binary_sensor.living_room_outside_window_vibration:
      device_class: vibration
    binary_sensor.living_room_motion:
      device_class: motion
    binary_sensor.litter_box_pan:
      device_class: door
      icon: mdi:paw
    light.living_room_floor_lamp:
      icon: mdi:floor-lamp
    sensor.pet_water_fountain:
      icon: mdi:cup-water
      hidden: true
    sensor.litter_box:
      icon: mdi:paw
      hidden: true
    switch.living_room_television_off:
      icon: mdi:television
      hidden: true
    switch.living_room_television:
      icon: mdi:television
      assumed_state: true
      
group:
  living_room_occupancy:
    name: Living Room Occupancy
    icon: mdi:account-multiple
    entities:
      - binary_sensor.living_room_motion
  living_room_protection:
    name: Living Room Protection
    icon: mdi:security
    entities:
      - binary_sensor.living_room_inside_window
      - binary_sensor.living_room_inside_window_vibration
      - binary_sensor.living_room_outside_window
      - binary_sensor.living_room_outside_window_vibration
  living_room:
    name: Living Room
    control: hidden
    entities:
      - group.living_room_occupancy
      - binary_sensor.living_room_inside_window
      - binary_sensor.living_room_inside_window_vibration
      - binary_sensor.living_room_outside_window
      - binary_sensor.living_room_outside_window_vibration
      - binary_sensor.living_room_motion
      - sensor.living_room_battery
      - light.living_room_floor_lamp
      - switch.living_room_television
      - media_player.living_room_home
      - media_player.living_room_television
      - sensor.living_room_motion_temperature
      - sensor.living_room_inside_window_temperature
      - sensor.living_room_outside_window_temperature
      - input_boolean.notify_living_room
      - input_boolean.security_living_room
  pets:
    name: House Pets
    control: hidden
    entities:
      - automation.pets_without_water_notification
      - automation.pets_without_litter_notification
      - binary_sensor.litter_box_pan
      - input_datetime.litter_emptied
      
# Living Room Interactivity
      
automation:
  - id: 'LivingRoomOccupied'
    alias: Living Room Occupied
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.living_room_occupancy
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('alarm_control_panel.main_residence') not in ['armed_away','pending','triggered'] }}"
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
    action:
      service: light.turn_on
      data_template:
        entity_id: light.living_room_floor_lamp
        brightness_pct: >
          {%if is_state('alarm_control_panel.lower_residence', 'armed_night') 
            or is_state('alarm_control_panel.upper_residence', 'armed_night') %}20{% else %}100{% endif %}
  - id: 'LivingRoomUnoccupied'
    alias: Living Room Unoccupied
    initial_state: on
    trigger:
      platform: state
      entity_id: group.living_room_occupancy
      to: 'off'
      for:
        minutes: 3
    condition:
      condition: state
      entity_id: light.living_room_floor_lamp
      state: 'on'
    action:
      service: light.turn_off
      data:
        entity_id: light.living_room_floor_lamp

  - id: 'PetsWithoutWater'
    alias: Pets Without Water
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.pet_water_fountain
      below: 1.1
      for:
        minutes: 90
    action:
      service: automation.turn_on
      entity_id: automation.pets_without_water_notification
  - id: 'PetsWatered'
    alias: Pets Watered
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.pet_water_fountain
      above: 1.1
    condition:
      condition: state
      entity_id: automation.pets_without_water_notification
      state: 'on'
    action:
      - service: automation.turn_off
        entity_id: automation.pets_without_water_notification
      - service: script.notify
        data:
          tell: residents
          message: "the Pet Fountain has returned to normal operation, thank you!"
  - id: 'PetsWithoutWaterNotification'
    alias: Pets Without Water Notification
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: automation.pets_without_water_notification
        to: 'on'
      - platform: time
        hours: '/1'
        minutes: 00
        seconds: 00
    action:
      service: script.notify
      data:
        tell: residents
        message: "the Pet Fountain has not been running for longer than usual.  You may need to add more water or change the current filter!"

  - id: 'PetsWithoutLitter'
    alias: Pets Without Litter
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.litter_box
      below: 6
      for: '00:10:00'
    action:
      service: automation.turn_on
      entity_id: automation.pets_without_litter_notification
  - id: 'PetsLittered'
    alias: Pets Littered
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id: sensor.litter_box
      above: 6
    condition:
      condition: state
      entity_id: automation.pets_without_litter_notification
      state: 'on'
    action:
      - service: automation.turn_off
        entity_id: automation.pets_without_litter_notification
      - service: script.notify
        data:
          tell: residents
          message: "the Litter Box has returned to normal operation, thank you!"
  - id: 'PetsWithoutLitterNotification'
    alias: Pets Without Litter Notification
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: automation.pets_without_litter_notification
        to: 'on'
      - platform: time
        hours: '/1'
        minutes: 00
        seconds: 00
    action:
      service: script.notify
      data:
        tell: residents
        message: "the Litter Box has not been running for longer than usual.  You may need to check if the bin is full!"
  - id: 'LitterBoxEmptied'
    alias: Litter Box Emptied
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.litter_box_pan
        to: 'on'
    action:
      - service: input_datetime.set_datetime
        data_template:
          entity_id: input_datetime.litter_emptied
          date: "{{ now().year }}-{{ now().month }}-{{ now().day }}"
      - service: switch.turn_off
        entity_id: switch.pets_without_litter_notification
        
  - id: 'LivingRoomAlarm'
    alias: Living Room Alarm
    initial_state: on
    trigger:
    - entity_id: group.living_room_protection
      platform: state
      to: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.smart_security_system
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.smart_security_system
          state: armed_away
    action:
    - data:
        entity_id: alarm_control_panel.smart_security_system
      service: alarm_control_panel.alarm_trigger