group:
  all_lower_residence:
    name: All Lower Residence
    entities:
      - light.master_bedroom_floor_lamp
      - light.williams_bedside_lamp
      - light.mikes_bedside_lamp
      - light.office_lights
      - switch.studio_lights
      - switch.office_monitors
      - switch.studio_office_television

automation:
  - id: LowerResidenceWaking
    alias: Lower Residence Waking
    initial_state: on
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.master_bathroom_shower
          - light.master_bedroom_floor_lamp
        to: 'on'
    condition:
      condition: state
      entity_id: alarm_control_panel.lower_residence
      state: armed_night
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.william_status_selector
          option: Waking
      - service: alarm_control_panel.alarm_arm_home
        entity_id: alarm_control_panel.lower_residence
      - service: script.notify
        data:
          no_notify: true
          no_inform: true
          tell: william
          message: it appears you are waking for the day!  I've prepared the residence for you.
  - id: LowerResidenceAwake
    alias: Lower Residence Awake
    initial_state: on
    trigger:
      - platform: state
        entity_id: sensor.william_status
        to: Waking
        for: '00:03:00'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.william_status_selector
          option: Home
  - id: LowerResidenceNight
    alias: Lower Residence Night
    initial_state: on
    trigger:
      - platform: template
        value_template: "{{ states('sensor.william_mobile_phone') not in ['On Person'] }}"
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('alarm_control_panel.lower_residence') not in ['armed_night'] }}"
        - condition: state
          entity_id: script.night_check
          state: 'off'
        - condition: state
          entity_id: binary_sensor.studio_office_door
          state: 'off'
    action:
      - service: script.night_check
      - delay: '00:00:02'
      - wait_template: "{{ is_state('script.night_check','off') }}"
        timeout: '00:03:00'
        continue_on_timeout: 'false'
      - service: input_select.select_option
        data:
          entity_id: input_select.william_status_selector
          option: Sleeping
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.lower_residence
      - service: script.night_lower_residence
      - service: script.night_main_residence
        data: 
          residence: lower
      - service: script.night_downstairs_hall
      - service: script.night_living_room
      - service: script.night_kitchen_dinette
      - service: script.night_climate
      
script:
  night_check:
    sequence:
      - service: script.notify
        data_template:
          no_notify: true
          no_inform: true
          tell: william
          where: master_bedroom_home
          message: >
            It {{ ['appears','looks','seems']|random + ' ' +['like','as though','as if','that']|random + ' ' -}}
            you are {{ ['preparing for','going to','getting ready for']|random + ' ' + ['bed','sleep']|random }} now.
            {% if is_state('binary_sensor.william_medicated_recently','off') %}
            {{ ["You should know that","I'd like to bring to your attention that","I'm sorry but","I should inform you that"]|random + ', ' -}}
            you {{ ["haven't taken","have not taken","seem to have forgotten","have missed taking"]|random + ' ' }}
            your medication. Before I adjust the residence, please take your medication!{% endif %}
            {% if is_state('sensor.william_fitness_tracker','Worn') %}
            It looks like you're still wearing your fitness tracker.  Please charge it before you sleep!{% endif %}
      - wait_template: "{{ is_state('binary_sensor.william_medicated_recently','on') 
                        and not is_state('sensor.william_fitness_tracker','Worn')}}"
        timeout: '00:03:30'
        continue_on_timeout: 'false'
      - delay: '00:00:03'
      - wait_template: "{{ is_state('input_boolean.saying_notification','off') }}"
      - service: script.notify
        data_template:
          no_notify: true
          no_greet: true
          no_inform: true
          tell: william
          where: master_bedroom_home
          message: >
            I'm adjusting the residence to your {{ ['night time','bed time','sleeping']|random }}
            {{ ['preferences','desires','wishes']|random }}.
            {{ ['Nighty night','Go to bed, you sleepy head','Sleep tight','Sweet dreams']|random }}!
            {{ ["I'll see you tomorrow","I'm here if you need me","I'll see you in the morning"]|random }}
  night_lower_residence:
    sequence:
      - service: homeassistant.turn_off
        entity_id: group.all_lower_residence
  night_main_residence:
    sequence:
      - condition: or
        conditions:
          - condition: state
            entity_id: group.living_room_occupancy
            state: 'on'
          - condition: state
            entity_id: group.kitchen_dinette_occupancy
            state: 'on'
      - service: script.notify
        data_template:
          no_notify: true
          tell: everyone
          where: living_room_home
          message: >
            the {{ residence }} residence is going to sleep now. 
            I'm adjusting the main residence ambiance accordingly!
  night_downstairs_hall:
    sequence:
      - condition: state
        entity_id: light.downstairs_hall_light
        state: 'on'
      - service: light.turn_on
        data: 
          entity_id: light.downstairs_hall_light
          brightness_pct: 10
      - delay: '00:00:01'
      - service: light.turn_off
        entity_id: light.downstairs_hall_light
  night_living_room:
    sequence:
      - condition: state
        entity_id: light.living_room_floor_lamp
        state: 'on'
      - service: light.turn_on
        data: 
          entity_id: light.living_room_floor_lamp
          brightness_pct: 20
      - service: switch.turn_off
        entity_id: switch.entry_light
  night_kitchen_dinette:
    sequence:
      - condition: state
        entity_id: light.kitchen_light
        state: 'on'
      - service: light.turn_on
        data: 
          entity_id: light.kitchen_light
          brightness_pct: 20
      - condition: state
        entity_id: light.dinette_light
        state: 'on'
      - service: light.turn_on
        data: 
          entity_id: light.dinette_light
          brightness_pct: 20
  night_climate:
    sequence:
      - service: climate.set_temperature
        data:
          entity_id: climate.thermostat
          temperature: 66