# Master Bathroom Sensors

binary_sensor:
  - platform: mqtt
    state_topic: "smartthings/Master Bathroom/motion/state"
    name: "Master Bathroom Motion"
    payload_on: active
    payload_off: inactive
  - platform: trend
    sensors:
      master_bathroom_shower:
        entity_id: sensor.downstairs_hall_halo_humidity
        device_class: moisture
        sample_duration: 180

sensor:
  - platform: mqtt
    state_topic: "smartthings/Master Bathroom/temperature/state"
    name: "Master Bathroom Motion Temperature"
    unit_of_measurement: '°F'

# Master Bathroom Interface
    
homeassistant:
  customize:
    binary_sensor.master_bathroom_motion:
      device_class: motion
      
group:
  master_bathroom_occupancy:
    name: Master Bathroom Occupancy
    icon: mdi:account-multiple
    entities:
      - binary_sensor.master_bathroom_motion
  master_bathroom:
    name: Master Bathroom
    control: hidden
    entities:
      - group.master_bathroom_occupancy
      - binary_sensor.master_bathroom_motion
      - binary_sensor.master_bathroom_shower
      - sensor.william_fitness_tracker
      - sensor.master_bathroom_battery
      - sensor.master_bathroom_motion_temperature
      
automation:
  - id: 'MirrorDriedAfterShowering'
    alias: Mirror Dried After Showering
    initial_state: on
    trigger:
      - platform: state
        entity_id: binary_sensor.master_bathroom_shower
        from: 'on'
        to: 'off'
    action:
      - wait_template: "{{ states('sensor.downstairs_hall_halo_humidity') < '60' }}"
      - service: script.notify
        data:
          no_notify: true
          where: lower_residence
          message: the mirror in the Master Bathroom should no longer be fogged over.