# Master Bedroom Devices:

light:
  - platform: mqtt
    name: "Master Bedroom Floor Lamp"
    command_topic: "smartthings/Master Bedroom Floor Lamp/switch/cmd"
    brightness_command_topic: "smartthings/Master Bedroom Floor Lamp/level/cmd"
    brightness_state_topic: "smartthings/Master Bedroom Floor Lamp/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    state_topic: "smartthings/Master Bedroom Floor Lamp/switch/state"
  - platform: mqtt
    name: "Mike's Bedside Lamp"
    command_topic: "smartthings/Mike's Bedside Lamp/switch/cmd"
    brightness_command_topic: "smartthings/Mike's Bedside Lamp/level/cmd"
    brightness_state_topic: "smartthings/Mike's Bedside Lamp/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    state_topic: "smartthings/Mike's Bedside Lamp/switch/state"
  - platform: mqtt
    name: "William's Bedside Lamp"
    command_topic: "smartthings/William's Bedside Lamp/switch/cmd"
    brightness_command_topic: "smartthings/William's Bedside Lamp/level/cmd"
    brightness_state_topic: "smartthings/William's Bedside Lamp/level"
    brightness_scale: 100
    payload_on: "on"
    payload_off: "off"
    state_topic: "smartthings/William's Bedside Lamp/switch/state"
    
switch:
  - platform: tplink
    host: 10.99.99.3
    name: Master Bedroom Power Strip
    
# Master Bedroom Sensor

binary_sensor:
  - platform: mqtt
    state_topic: "smartthings/Master Bedroom Window/contact/state"
    name: "Master Bedroom Window"
    payload_on: open
    payload_off: closed
  - platform: mqtt
    state_topic: "smartthings/Master Bedroom/motion/state"
    name: "Master Bedroom Motion"
    payload_on: active
    payload_off: inactive
    
sensor:
  - platform: mqtt
    state_topic: "smartthings/Master Bedroom/temperature/state"
    name: "Master Bedroom Motion Temperature"
    unit_of_measurement: '°F'
  - platform: mqtt
    state_topic: "smartthings/Master Bedroom Window/temperature/state"
    name: "Master Bedroom Window Temperature"
    unit_of_measurement: '°F'
  - platform: mqtt
    state_topic: "smartthings/William's Watch Charger/power/state"
    name: "William Watch Charger"
    unit_of_measurement: 'W'
  - platform: template
    sensors:
      william_fitness_tracker:
        friendly_name: William's Fitness Tracker
        value_template: >
          {% if states('sensor.william_watch_charger') > '1'  %}
            Charging
          {% elif states('sensor.william_watch_charger') > '0' %}
            Charged
          {% else %}
            Worn
          {% endif %}
      william_mobile_phone:
        friendly_name: William's Mobile Phone
        value_template: >
          {% if states('sensor.william_mobile_charger') > '3'  %}
            Charging
          {% elif states('sensor.william_mobile_charger') > '1' %}
            Charged
          {% else %}
            On Person
          {% endif %}
      william_mobile_charger:
        friendly_name: William's Mobile Charger
        value_template: "{{ state_attr('switch.master_bedroom_power_strip','current_power_w') }}"
        unit_of_measurement: 'W'

# Master Bedroom Inputs    
    
input_boolean:
  wakeup_william:
    name: Wakeup William
    icon: mdi:alarm-check
  wakeup_partner:
    name: Wakeup Partner
    icon: mdi:alarm-check

input_datetime:
  wakeup_william:
    name: Wakeup William At
    icon: mdi:alarm
    has_time: true
  wakeup_partner:
    name: Wakeup Partner At
    icon: mdi:alarm
    has_time: true

    
# Master Bedroom Interface
    
homeassistant:
  customize:
    binary_sensor.master_bedroom_window:
      device_class: window
    binary_sensor.master_bedroom_motion:
      device_class: motion
    light.master_bedroom_floor_lamp:
      icon: mdi:floor-lamp
    light.williams_bedside_lamp:
      icon: mdi:lamp
    light.mikes_bedside_lamp:
      icon: mdi:lamp
    sensor.william_mobile_phone:
      icon: mdi:cellphone-android
      
group:
  master_bedroom_wakeup:
    name: Master Bedroom Wakeup
    icon: mdi:alarm-multiple
    control: hidden
    entities:
      - input_boolean.wakeup_william
      - input_datetime.wakeup_william
      - input_boolean.wakeup_partner
      - input_datetime.wakeup_partner
  master_bedroom_occupancy:
    name: Master Bedroom Occupancy
    icon: mdi:account-multiple
    entities:
      - binary_sensor.master_bedroom_motion    
  master_bedroom_protection:
    name: Master Bedroom Protection
    icon: mdi:security
    entities:
      - binary_sensor.master_bedroom_window
  master_bedroom:
    name: Master Bedroom
    control: hidden
    entities:
      - group.master_bedroom_occupancy
      - binary_sensor.master_bedroom_motion
      - binary_sensor.master_bedroom_window
      - light.master_bedroom_floor_lamp
      - light.williams_bedside_lamp
      - light.mikes_bedside_lamp
      - sensor.william_mobile_phone
      - media_player.master_bedroom_home
      - media_player.master_bedroom_un32j5303
      - sensor.master_bedroom_window_temperature
      - sensor.master_bedroom_motion_temperature
      - input_boolean.notify_master_bedroom
      - input_boolean.security_master_bedroom
      
automation:
  - id: 'MasterBedroomOccupied'
    alias: Master Bedroom Occupied
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.master_bedroom_occupancy
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ states('alarm_control_panel.lower_residence') not in ['armed_away','armed_night','pending','triggered'] }}"
        - condition: or
          conditions:
            - condition: sun
              after: sunset
            - condition: sun
              before: sunrise
    action:
      service: light.turn_on
      data:
        entity_id: light.master_bedroom_floor_lamp
        brightness_pct: 50
  - id: 'MasterBedroomUnoccupied'
    alias: Master Bedroom Unoccupied
    initial_state: on
    trigger:
      platform: state
      entity_id: group.master_bedroom_occupancy
      to: 'off'
      for: '00:03:00'
    condition:
      condition: state
      entity_id: light.master_bedroom_floor_lamp
      state: 'on'
    action:
      service: light.turn_off
      data:
        entity_id: light.master_bedroom_floor_lamp