wake_on_lan:
zeroconf:
      
sensor:
  - platform: dnsip
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload

device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret default_password
    detection_time: 120
      
homeassistant:
  customize:
    sensor.myip:
      friendly_name: External Address
      icon: mdi:ip-network
      
group:
  wide_area_network:
    name: Wide Area Network
    control: hidden
    entities:
      - sensor.myip
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
  local_area_network:
    name: Local Area Network
    control: hidden
    entities:
      - device_tracker.cloudkey
      - device_tracker.smartthings
      - device_tracker.hassio
      - device_tracker.ringfrontdoorbell
      - device_tracker.thermostat
      - device_tracker.petfeeder
      - device_tracker.fitbodyscale
      - device_tracker.stripmasterbed
  print_scan_devices:
    name: Print & Scan Devices
    control: hidden
    entities:
      - device_tracker.printinkjet
      - device_tracker.printlaser
  media_devices:
    name: Media Devices
    control: hidden
    entities:
      - device_tracker.tvstudiooffice
      - device_tracker.tvlivingroom
      - device_tracker.tvbrlivingroom
      - device_tracker.wiiu
  user_devices:
    name: User Devices
    control: hidden
    entities:
      - device_tracker.pcgeektop
      - device_tracker.geekbook
      - device_tracker.tabgeektab
      - device_tracker.pcjordan
  google_cast_devices:
    name: Google Cast Devices
    control: hidden
    entities:
      - device_tracker.ghlivingroom
      - device_tracker.cclivingroom
      - device_tracker.ghmasterbath
      - device_tracker.ghmasterbed
      - device_tracker.ghstudiooffice
      - device_tracker.ccstudiooffice
      - device_tracker.ghupstairsbed
  video_survelliance:
    name: Video Surveillance
    control: hidden
    entities:
      - device_tracker.nvr
      - device_tracker.camoffice
      
automation:
  - id: 'ExternalIPChanged'
    alias: External IP Changed
    initial_state: on
    trigger:
      - platform: state
        entity_id: sensor.myip
        from: !secret external_staticip
    action:
      service: script.notify
      data_template:
        tell: residents
        message: >
          the primary internet connection is unavailable.  I've successfully enabled the wireless backup connection!  Should you need to connect remotely, the current IP Address is: "{{ states('sensor.myip') }}"
  - id: 'ExternalIPRestored'
    alias: External IP Restored
    initial_state: on
    trigger:
      - platform: state
        entity_id: sensor.myip
        to: !secret external_staticip
    action:
      service: script.notify
      data_template:
        tell: residents
        message: >
          the primary internet connection has been restored, remote connections can be made as normal!