sun:

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - minutely_summary
      - hourly_summary
      - daily_summary
      - precip_type
      - precip_intensity
      - precip_probability
      - precip_accumulation
      - apparent_temperature
      - temperature
      - temperature_high
      - temperature_low
      - wind_speed
      - cloud_cover
      - humidity
      - uv_index
  - platform: moon
  
input_datetime:
  wastebins_out:
    name: Wastebins Taken Out
    has_date: true
    icon: mdi:trash-can
  wastebins_in:
    name: Wastebins Taken In
    has_date: true
    icon: mdi:trash-can-outline
    
group:
  wastebins:
    name: Wastebins
    entities:
      - input_datetime.wastebins_out
      - input_datetime.wastebins_in
  vehicles:
    name: Vehicles
    entities:
      - device_tracker.fordescape
  weather:
    name: Weather
    control: hidden
    entities:
      - sun.sun
      - sensor.moon
      - sensor.dark_sky_summary
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daytime_high_temperature
      - sensor.dark_sky_humidity
      - sensor.dark_sky_overnight_low_temperature
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_accumulation
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_wind_speed