device_tracker:
  - platform: mqtt
    devices:
      william_smartthings: "smartthings/William's Mobile Phone/presence/state"
      jordan_smartthings: "smartthings/Jordan's Mobile Phone/presence/state"

sensor:
  - platform: template
    sensors:
      william_status: 
        value_template: '{{ states.input_select.william_status_selector.state }}'
        friendly_name: 'William'
      jordan_status: 
        value_template: '{{ states.input_select.jordan_status_selector.state }}'
        friendly_name: 'Jordan'
      
input_number:
  william_recently_away:
    name: William Recently Away
    initial: 0
    min: 0
    max: 9
    step: 1
  jordan_recently_away:
    name: Jordan Recently Away
    initial: 0
    min: 0
    max: 9
    step: 1
      
input_select:
  william_status_selector:
    name: William's Status
    options:
      - 'Unknown'
      - 'Vacation'
      - 'Extended Away'
      - 'Away'
      - 'Departed'
      - 'Arriving'
      - 'Arrived'
      - 'Home'
      - 'Showering'
      - 'Waking'
      - 'Sleeping'
  jordan_status_selector:
    name: Jordan's Status
    options:
      - 'Unknown'
      - 'Vacation'
      - 'Extended Away'
      - 'Away'
      - 'Departed'
      - 'Arriving'
      - 'Arrived'
      - 'Home'
      - 'Showering'
      - 'Waking'
      - 'Sleeping'
      
zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 10

homeassistant:      
  customize:
    sensor.william_status:
      entity_picture: http://graph.facebook.com/100000294423973/picture?type=square
    sensor.jordan_status:
      entity_picture: http://graph.facebook.com/100001037480248/picture?type=square
    device_tracker.william_owntracks:
      icon: mdi:map-marker-radius
    device_tracker.william_smartthings:
      icon: mdi:map-marker-radius
    device_tracker.jordan_smartthings:
      icon: mdi:map-marker-radius
    device_tracker.william_mobile_wifi:
      icon: mdi:cellphone-wireless
    device_tracker.jordan_mobile_wifi:
      icon: mdi:cellphone-wireless
    device_tracker.william_watch_wifi:
      icon: mdi:watch
    device_tracker.william_fordescape_wifi:
      icon: mdi:car-connected
    
group:
  williams_presence:
    name: "William's Presence"
    entities:
      - device_tracker.william_smartthings
      - device_tracker.william_owntracks
      - device_tracker.william_mobile_wifi
      - device_tracker.william_watch_wifi
      - device_tracker.william_fordescape_wifi
  jordans_presence:
    name: "Jordan's Presence"
    entities:
      - device_tracker.jordan_smartthings
      - device_tracker.jordan_mobile_wifi
  residents:
    name: "Residents"
    entities:
      - sensor.william_status
      - sensor.jordan_status

automation:
  - id: 'Presence Arrived'
    alias: Presence Arrived
    initial_state: on
    trigger:
      - platform: state
        entity_id: 
          - device_tracker.william_smartthings
          - device_tracker.jordan_smartthings
        to: 'present'
      - platform: state
        entity_id: 
          - device_tracker.william_owntracks
          - device_tracker.william_mobile_wifi
          - device_tracker.william_watch_wifi
          - device_tracker.william_fordescape_wifi
          - device_tracker.jordan_mobile_wifi
        to: 'home'
    condition:
      condition: template
      value_template: >
        {{ ( trigger.entity_id.split('.')[1].split('_')[0] == 'william' 
        and states('input_select.william_status_selector') != 'Home' ) or
        ( trigger.entity_id.split('.')[1].split('_')[0] == 'jordan'
        and states('input_select.jordan_status_selector') != 'Home' ) }}
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id.split('.')[1].split('_')[0] == 'william' %}
              input_select.william_status_selector
            {% elif trigger.entity_id.split('.')[1].split('_')[0] == 'jordan' %}
              input_select.jordan_status_selector
            {% endif %}
          option: 'Arrived'
  - id: 'Presence Home'
    alias: Presence Home
    initial_state: on
    trigger:
      - platform: state
        entity_id:
          - input_select.william_status_selector
          - input_select.jordan_status_selector
        to: 'Arrived'
        for: '00:02:00'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id.split('.')[1].split('_')[0] == 'william' %}
              input_select.william_status_selector
            {% elif trigger.entity_id.split('.')[1].split('_')[0] == 'jordan' %}
              input_select.jordan_status_selector
            {% endif %}
          option: 'Home'
  - id: 'Presence Recently Departed'
    alias: Presence Recently Departed
    initial_state: on
    trigger:
      - platform: state
        entity_id: 
          - device_tracker.william_smartthings
          - device_tracker.jordan_smartthings
        to: 'not present'
      - platform: state
        entity_id: 
          - device_tracker.william_owntracks
          - device_tracker.william_mobile_wifi
          - device_tracker.william_watch_wifi
          - device_tracker.william_fordescape_wifi
          - device_tracker.jordan_mobile_wifi
        to: 'not_home'
    action:
      - service: input_number.increment
        data_template:
          entity_id: >
            {% if trigger.entity_id.split('.')[1].split('_')[0] == 'william' %}
              input_number.william_recently_away
            {% elif trigger.entity_id.split('.')[1].split('_')[0] == 'jordan' %}
              input_number.jordan_recently_away
            {% endif %}
  - id: 'Presence Away Timeout'
    alias: Presence Away Timeout
    initial_state: on
    trigger:
      platform: numeric_state
      entity_id:
        - input_number.william_recently_away
        - input_number.jordan_recently_away
      above: 0
      for: '00:03:00'
    action:
     - service: input_number.set_value
       data_template:
         entity_id: "{{ trigger.entity_id }}"
         value: 0
  - id: 'Presence Away'
    alias: Presence Away
    initial_state: on
    trigger:
      - platform: state
        entity_id:
          - sensor.william_status
          - sensor.jordan_status
        to: 'Departed'
        for: '00:02:00'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: >
            {% if trigger.entity_id.split('.')[1].split('_')[0] == 'william' %}
              input_select.william_status_selector
            {% elif trigger.entity_id.split('.')[1].split('_')[0] == 'jordan' %}
              input_select.jordan_status_selector
            {% endif %}
          option: 'Away'
    
  - id: 'AllOccupantsAway'
    alias: All Occupants Away
    initial_state: on
    trigger:
      platform: state
      entity_id: group.residents
      to: not_home
    action:
      - service: script.notify
        data:
          no_say: true
          tell: residents
          message: "everyone has left the premise.  I'm now securing the entire residence!"
      - delay:
          seconds: 1
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.upper_residence
      - delay:
          seconds: 1
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.lower_residence
      - service: homeassistant.turn_off
        entity_id: group.all_lower_residence
      - delay:
          seconds: 1
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.main_residence
  - id: 'WilliamsDeparture'
    alias: William's Departure
    initial_state: on
    trigger:
      - platform: state
        entity_id: group.williams_presence
        to: not_home
      - platform: numeric_state
        entity_id: input_number.william_recently_away
        above: 1
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.william_status_selector
          option: 'Departed'
      - condition: state
        entity_id: group.residents
        state: home
      - service: script.notify
        data:
          no_say: true
          tell: william
          departing: true
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.lower_residence
      - service: homeassistant.turn_off
        entity_id: group.all_lower_residence
  - id: 'JordansDeparture'
    alias: Jordan's Departure
    initial_state: on
    trigger:
      platform: state
      entity_id: group.jordans_presence
      to: not_home
    action:
      - service: script.notify
        data:
          where: downstairs
          departed: jordan
      - condition: state
        entity_id: group.residents
        state: home
      - service: script.notify
        data:
          no_say: true
          tell: jordan
          departing: true
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.upper_residence