# System Sensors

sensor:
  - platform: scrape
    name: Latest Release
    resource: https://www.home-assistant.io
    select: ".current-version h1"
    value_template: '{{ value.split(" ")[2] }}'
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: ipv4_address
        arg: eth0
      - type: last_boot
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: version
 
# System Inputs

input_boolean:
  maintenance_mode:
    name: Maintenance Mode
    icon: mdi:toolbox

input_datetime:
  briefing_william:
    name: William's Briefing
    has_date: true
    has_time: true
  briefing_mike:
    name: Mike's Briefing
    has_date: true
    has_time: true
  briefing_jordan:
    name: Jordan's Briefing
    has_date: true
    has_time: true

# System Interface
    
group:
  outside:
    view: yes
    name: Outside
    control: hidden
    entities:
      - group.wastebins
      - group.front_yard
      - group.back_yard
      - group.weather
  main_residence:
    view: yes
    name: Main Residence
    control: hidden
    entities:
      - climate.thermostat
      - group.front_entrance
      - group.living_room
      - group.kitchen_dinette
      - group.downstairs_hall
  lower_residence:
    view: yes
    name: Lower Residence
    control: hidden
    entities:
      - climate.thermostat
      - group.all_lower_residence
      - group.downstairs_hall
      - group.master_bathroom
      - group.master_bedroom
      - group.master_bedroom_wakeup
      - group.studio_office
  people:
    view: yes
    name: People
    control: hidden
    entities:
      - group.residents
      - group.williams_presence
      - group.william_health_fitness
      - group.jordans_presence
  networking:
    view: yes
    name: Networking
    control: hidden
    entities:
      - group.wide_area_network
      - group.local_area_network
      - group.print_scan_devices
      - group.media_devices
      - group.user_devices
      - group.google_cast_devices
  systems:
    view: yes
    name: Systems
    control: hidden
    entities:
      - group.system_info
      - group.front_doorbell_status
      - group.front_door_lock_status
  system_info:
    name: System Information
    control: hidden
    entities:
      - sensor.date
      - sensor.time
      - sensor.disk_use_percent_
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.ipv4_address_eth0
      - sensor.current_version
      - sensor.latest_release
      - sensor.last_boot
      - input_boolean.maintenance_mode

# System Interactivity
      
automation:
  - id: 'HomeAssistantStartup'
    alias: Home Assistant Startup
    initial_state: on
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: script.notify
        data_template:
          tell: everyone
          message: "my systems were successfully restarted and are back online!"
  - id: 'MaintenanceEnabled'
    alias: Maintenance Enabled
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.maintenance_mode
      to: 'on'
    action:
      service: script.notify
      data:
        tell: everyone
        message: "maintenance mode has been enabled.  During this time, some of my functionality may
        become limited or I may not respond as you would expect.  Please disregard any unusual
        behavior while my systems are sorted.  Also note, some notifications will be temporarily unavailble!"
  - id: 'MaintenanceDisabled'
    alias: Maintenance Disabled
    initial_state: on
    trigger:
      platform: state
      entity_id: input_boolean.maintenance_mode
      to: 'off'
    action:
      service: script.notify
      data:
        tell: everyone
        message: "maintenance mode has been disabled.  At this time my systems should be fully
        functional.  If you experience any issues, please report them immediately.  Thank you!"
  - id: 'IFTTTEventHandler'
    alias: IFTTT Event Handler
    initial_state: on
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
    action:
      service_template: '{{ trigger.event.data.service }}'
      data_template:
        entity_id: '{{ trigger.event.data.entity_id }}'