amcrest:
  - host: !secret camera_nvr
    name: Network Video Recorder
    username: admin
    password: !secret default_password
    switches:
      - motion_recording
  - host: !secret camera_studiooffice
    name: Studio Office
    username: admin
    password: !secret default_password
    sensors:
      - motion_detector

ring:
  username: !secret williams_email
  password: !secret default_password      

camera:
  - platform: amcrest
  - platform: ring
  
homeassistant:
  customize:
    camera.nvr:
      hidden: true